version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    #volumes:
    #  - ./data/namesrv/logs:/root/logs
    #  - ./data/namesrv/store:/root/store
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      #- NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-XX:ParallelGCThreads=4
    #volumes:
    #  - ./data/broker/logs:/root/logs
    #  - ./data/broker/store:/root/store
    command: sh mqbroker -n namesrv:9876
    depends_on:
      - namesrv
  console:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    ports:
      - 8080:8080
    depends_on:
      - namesrv
      - broker
  client:
    image: wanliqun/rocketmq-client:1.0
    container_name: rmqclient
    volumes:
      - /d/workspace/goroot/src/deepchain-worker:/go/src/deepchain-worker
    command: tail -f /dev/null
    depends_on:
      - namesrv
      - broker
